trigger:
  - main
    
pr:
  - main

pool:
  name: 'Stackworx'

resources:
  repositories:
    - repository: templates
      name: BuildTemplates/templates
      type: git

# variables:
#   - group: ci
  
stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - template: node-library.yml@templates
            parameters:
              nodeVersion: '20.x'
              script: |
                npm run fmt:check
                npm run typecheck
                npm run test
                npm run build

  -  ${{ if startsWith(variables['Build.SourceBranch'], 'refs/tags/') }}
    - stage: Publish
      jobs:
        - job: Publish
          steps:
            - task: DownloadPipelineArtifact@2
              inputs:
                targetPath: dist
            - task: NodeTool@0
              displayName: Install Node
              inputs:
                versionSource: 'spec'
                versionSpec: '20.x'
            - task: Npm@1:
              inputs:
                command: custom
                
            - task: Npm@1
              inputs:
                command: publish
                customCommand: version --no-git-tag-version variables['Build.SourceBranchName']
                publishRegistry: useFeed
                publishFeed: '$(System.TeamProjectId)/React'